const str = "Привіт";
const strMode = typeof str;
console.log(strMode);
const num = 123;
const numMode = typeof num;
console.log(numMode);
const flag = true;
const flagMode = typeof flag;
console.log(flagMode);
const txt = "true";
const txtMode = typeof txt;
console.log(txtMode);